# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'static/ui/addevent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_AddEvent(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 550)
        Dialog.setStyleSheet("background-color: #ffe6d8;")
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(0, 60, 651, 491))
        self.background.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.headerLabelText = QtWidgets.QLabel(Dialog)
        self.headerLabelText.setGeometry(QtCore.QRect(120, 0, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabelText.setFont(font)
        self.headerLabelText.setStyleSheet("color: #281401;\n"
"padding-left: 50px;\n"
"")
        self.headerLabelText.setObjectName("windowText")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(160, 110, 341, 281))
        self.frame.setStyleSheet("background-color:none;")
        self.frame.setObjectName("frame")
        self._2 = QtWidgets.QVBoxLayout(self.frame)
        self._2.setContentsMargins(1, -1, 1, -1)
        self._2.setSpacing(15)
        self._2.setObjectName("_2")
        self.eventName = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventName.sizePolicy().hasHeightForWidth())
        self.eventName.setSizePolicy(sizePolicy)
        self.eventName.setMinimumSize(QtCore.QSize(0, 50))
        self.eventName.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.eventName.setFont(font)
        self.eventName.setStyleSheet("QLineEdit{background-color: rgb(255, 255, 255);\n"
"  border-width: 1px;\n"
"  border-style: solid;\n"
"  border-color: #79747e;\n"
"  border-radius: 4px;\n"
"  gap: 10px;\n"
"padding-left: 10px;}\n"
"QLineEdit:focus{\n"
"border-color: #E77D66;\n"
"border-width: 2px;\n"
"}")
        self.eventName.setText("")
        self.eventName.setMaxLength(150)
        self.eventName.setCursorPosition(0)
        self.eventName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.eventName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.eventName.setObjectName("eventName")
        self._2.addWidget(self.eventName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eventDate = QtWidgets.QDateEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventDate.sizePolicy().hasHeightForWidth())
        self.eventDate.setSizePolicy(sizePolicy)
        self.eventDate.setMinimumSize(QtCore.QSize(0, 50))
        self.eventDate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.eventDate.setStyleSheet("QDateEdit{background-color: rgb(255, 255, 255);\n"
"  border-width: 1px;\n"
"  border-style: solid;\n"
"  border-color: #79747e;\n"
"  border-radius: 4px;\n"
"  gap: 10px;\n"
"padding-left: 10px;}\n"
"QDateEdit:focus{\n"
"border-color: #E77D66;\n"
"border-width: 2px;\n"
"}")
        self.eventDate.setFrame(True)
        self.eventDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.eventDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.eventDate.setObjectName("EventDate")
        self.horizontalLayout.addWidget(self.eventDate)
        self.eventTime = QtWidgets.QTimeEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventTime.sizePolicy().hasHeightForWidth())
        self.eventTime.setSizePolicy(sizePolicy)
        self.eventTime.setMinimumSize(QtCore.QSize(0, 50))
        self.eventTime.setMaximumSize(QtCore.QSize(16777215, 50))
        self.eventTime.setStyleSheet("QTimeEdit{background-color: rgb(255, 255, 255);\n"
"  border-width: 1px;\n"
"  border-style: solid;\n"
"  border-color: #79747e;\n"
"  border-radius: 4px;\n"
"  gap: 10px;\n"
"padding-left: 10px;}\n"
"QTimeEdit:focus{\n"
"border-color: #E77D66;\n"
"border-width: 2px;\n"
"}")
        self.eventTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.eventTime.setObjectName("EventTime")
        self.horizontalLayout.addWidget(self.eventTime)
        self._2.addLayout(self.horizontalLayout)
        self.eventBudget = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventBudget.sizePolicy().hasHeightForWidth())
        self.eventBudget.setSizePolicy(sizePolicy)
        self.eventBudget.setMinimumSize(QtCore.QSize(0, 50))
        self.eventBudget.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.eventBudget.setFont(font)
        self.eventBudget.setStyleSheet("QLineEdit{background-color: rgb(255, 255, 255);\n"
"  border-width: 1px;\n"
"  border-style: solid;\n"
"  border-color: #79747e;\n"
"  border-radius: 4px;\n"
"  gap: 10px;\n"
"padding-left: 10px;}\n"
"QLineEdit:focus{\n"
"border-color: #E77D66;\n"
"border-width: 2px;\n"
"}")
        self.eventBudget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.eventBudget.setText("")
        self.eventBudget.setMaxLength(32767)
        self.eventBudget.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.eventBudget.setCursorPosition(0)
        self.eventBudget.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.eventBudget.setObjectName("eventBudget")
        self._2.addWidget(self.eventBudget)
        self.radioBtnIsActive = QtWidgets.QRadioButton(self.frame)
        self.radioBtnIsActive.setMinimumSize(QtCore.QSize(0, 30))
        self.radioBtnIsActive.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.radioBtnIsActive.setFont(font)
        self.radioBtnIsActive.setStyleSheet("background-color:none;\n"
"  gap: 10px;\n"
"padding-left: 10px;")
        self.radioBtnIsActive.setObjectName("radioBtnIsActive")
        self._2.addWidget(self.radioBtnIsActive)
        self.radioBtnIsPlanned = QtWidgets.QRadioButton(self.frame)
        self.radioBtnIsPlanned.setMinimumSize(QtCore.QSize(0, 30))
        self.radioBtnIsPlanned.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.radioBtnIsPlanned.setFont(font)
        self.radioBtnIsPlanned.setStyleSheet("background-color:none;\n"
"  gap: 10px;\n"
"padding-left: 10px;")
        self.radioBtnIsPlanned.setObjectName("radioBtnIsPlanned")
        self._2.addWidget(self.radioBtnIsPlanned)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(150, 420, 361, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveEventDataBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveEventDataBtn.sizePolicy().hasHeightForWidth())
        self.saveEventDataBtn.setSizePolicy(sizePolicy)
        self.saveEventDataBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.saveEventDataBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.saveEventDataBtn.setFont(font)
        self.saveEventDataBtn.setStyleSheet("QPushButton{position: absolute;\n"
"color: rgb(255, 255, 255);\n"
"  background-color: #e77d66;\n"
"  border-radius: 20%;\n"
"  gap: 8px;\n"
"}")
        self.saveEventDataBtn.setObjectName("saveEventDataBtn")
        self.horizontalLayout_2.addWidget(self.saveEventDataBtn)
        self.deleteEventDataBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteEventDataBtn.sizePolicy().hasHeightForWidth())
        self.deleteEventDataBtn.setSizePolicy(sizePolicy)
        self.deleteEventDataBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.deleteEventDataBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.deleteEventDataBtn.setFont(font)
        self.deleteEventDataBtn.setStyleSheet("QPushButton{position: absolute;\n"
"color: rgb(255, 255, 255);\n"
"  background-color: #e77d66;\n"
"  border-radius: 20%;\n"
"  gap: 8px;\n"
"}")
        self.deleteEventDataBtn.setObjectName("deleteEventDataBtn")
        self.horizontalLayout_2.addWidget(self.deleteEventDataBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.headerLabelText.setText(_translate("Dialog", "Добавить мероприятие"))
        self.eventName.setPlaceholderText(_translate("Dialog", "Название мероприятия"))
        self.eventBudget.setPlaceholderText(_translate("Dialog", "Бюджет на мероприятие"))
        self.radioBtnIsActive.setText(_translate("Dialog", "Активно"))
        self.radioBtnIsPlanned.setText(_translate("Dialog", "Запланировано"))
        self.saveEventDataBtn.setText(_translate("Dialog", "Сохранить"))
        self.deleteEventDataBtn.setText(_translate("Dialog", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_AddEvent()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
