# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'static/ui/calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Calendar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 800)
        Dialog.setStyleSheet("background-color: #fadccb;\n"
"font-family: Roboto;")
        self.eventsBtn = QtWidgets.QPushButton(Dialog)
        self.eventsBtn.setGeometry(QtCore.QRect(0, 110, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventsBtn.sizePolicy().hasHeightForWidth())
        self.eventsBtn.setSizePolicy(sizePolicy)
        self.eventsBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.eventsBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.eventsBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.eventsBtn.setAutoFillBackground(False)
        self.eventsBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  gap: 4px;}\n"
"QPushButton:hover {\n"
"background: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}\n"
"")
        self.eventsBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/ui\\../img/events_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eventsBtn.setIcon(icon)
        self.eventsBtn.setIconSize(QtCore.QSize(85, 100))
        self.eventsBtn.setCheckable(False)
        self.eventsBtn.setAutoDefault(False)
        self.eventsBtn.setDefault(False)
        self.eventsBtn.setFlat(True)
        self.eventsBtn.setObjectName("eventsBtn")
        self.calendarBtn = QtWidgets.QPushButton(Dialog)
        self.calendarBtn.setGeometry(QtCore.QRect(0, 220, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarBtn.sizePolicy().hasHeightForWidth())
        self.calendarBtn.setSizePolicy(sizePolicy)
        self.calendarBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.calendarBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calendarBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.calendarBtn.setAutoFillBackground(False)
        self.calendarBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  gap: 4px;}\n"
"QPushButton:hover {\n"
"background: #FFF1ED;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}")
        self.calendarBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/ui\\../img/calendar_selected_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendarBtn.setIcon(icon1)
        self.calendarBtn.setIconSize(QtCore.QSize(85, 100))
        self.calendarBtn.setAutoDefault(False)
        self.calendarBtn.setDefault(False)
        self.calendarBtn.setFlat(True)
        self.calendarBtn.setObjectName("calendarBtn")
        self.topMenu = QtWidgets.QFrame(Dialog)
        self.topMenu.setGeometry(QtCore.QRect(110, 0, 971, 71))
        self.topMenu.setStyleSheet("padding: 0  50 0 0px;")
        self.topMenu.setObjectName("topMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topMenu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryText = QtWidgets.QLabel(self.topMenu)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.categoryText.setFont(font)
        self.categoryText.setStyleSheet("color: #281401;\n"
"padding-left: 50px;\n"
"")
        self.categoryText.setObjectName("categoryText")
        self.horizontalLayout.addWidget(self.categoryText)
        self.Background = QtWidgets.QLabel(Dialog)
        self.Background.setEnabled(True)
        self.Background.setGeometry(QtCore.QRect(110, 80, 991, 701))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        self.Background.setFont(font)
        self.Background.setStyleSheet("background-color: white;\n"
"    border-top-left-radius: 20px;")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.accountBtn = QtWidgets.QPushButton(Dialog)
        self.accountBtn.setGeometry(QtCore.QRect(0, 340, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountBtn.sizePolicy().hasHeightForWidth())
        self.accountBtn.setSizePolicy(sizePolicy)
        self.accountBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.accountBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.accountBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.accountBtn.setAutoFillBackground(False)
        self.accountBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  gap: 4px;}\n"
"QPushButton:hover {\n"
"background: #FFF1ED;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}")
        self.accountBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/ui\\../img/account_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountBtn.setIcon(icon2)
        self.accountBtn.setIconSize(QtCore.QSize(85, 100))
        self.accountBtn.setAutoDefault(False)
        self.accountBtn.setDefault(False)
        self.accountBtn.setFlat(True)
        self.accountBtn.setObjectName("accountBtn")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(140, 110, 521, 461))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("selection-background-color: #CA725F;")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.tasksBackground = QtWidgets.QLabel(Dialog)
        self.tasksBackground.setGeometry(QtCore.QRect(690, 110, 391, 641))
        self.tasksBackground.setText("")
        self.tasksBackground.setObjectName("tasksBackground")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 130, 282, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ChosenDate = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChosenDate.sizePolicy().hasHeightForWidth())
        self.ChosenDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ChosenDate.setFont(font)
        self.ChosenDate.setAlignment(QtCore.Qt.AlignCenter)
        self.ChosenDate.setObjectName("ChosenDate")
        self.verticalLayout.addWidget(self.ChosenDate)
        self.ToDoListLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToDoListLabel.sizePolicy().hasHeightForWidth())
        self.ToDoListLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.ToDoListLabel.setFont(font)
        self.ToDoListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ToDoListLabel.setObjectName("ToDoListLabel")
        self.verticalLayout.addWidget(self.ToDoListLabel)
        self.NoEventsLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoEventsLabel.sizePolicy().hasHeightForWidth())
        self.NoEventsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.NoEventsLabel.setFont(font)
        self.NoEventsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NoEventsLabel.setObjectName("NoEventsLabel")
        self.verticalLayout.addWidget(self.NoEventsLabel)
        self.showEventButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showEventButton.setMinimumSize(QtCore.QSize(280, 50))
        self.showEventButton.setMaximumSize(QtCore.QSize(280, 50))
        self.showEventButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20%;")
        self.showEventButton.setObjectName("showEventButton")
        self.verticalLayout.addWidget(self.showEventButton)
        self.Background.raise_()
        self.tasksBackground.raise_()
        self.layoutWidget.raise_()
        self.eventsBtn.raise_()
        self.calendarBtn.raise_()
        self.topMenu.raise_()
        self.accountBtn.raise_()
        self.calendarWidget.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.categoryText.setText(_translate("Dialog", "Календарь"))
        self.ChosenDate.setText(_translate("Dialog", "dd/mm/yyyy"))
        self.ToDoListLabel.setText(_translate("Dialog", "Мероприятия:"))
        self.NoEventsLabel.setText(_translate("Dialog", "Текст"))
        self.showEventButton.setText(_translate("Dialog", "Задача"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_Calendar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
