# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'static/ui/mainframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 799)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #fadccb;\n"
"font-family: Roboto;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topMenu = QtWidgets.QFrame(self.centralwidget)
        self.topMenu.setGeometry(QtCore.QRect(110, 20, 991, 71))
        self.topMenu.setStyleSheet("padding: 0  50 0 0px;")
        self.topMenu.setObjectName("topMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topMenu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryText = QtWidgets.QLabel(self.topMenu)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.categoryText.setFont(font)
        self.categoryText.setStyleSheet("color: #281401;\n"
"padding-left: 50px;\n"
"")
        self.categoryText.setObjectName("categoryText")
        self.horizontalLayout.addWidget(self.categoryText)
        self.addEventBtn = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addEventBtn.sizePolicy().hasHeightForWidth())
        self.addEventBtn.setSizePolicy(sizePolicy)
        self.addEventBtn.setMaximumSize(QtCore.QSize(170, 50))
        self.addEventBtn.setBaseSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.addEventBtn.setFont(font)
        self.addEventBtn.setStyleSheet("QPushButton{color: #281401;\n"
"  position: relative;\n"
"  width: 100%;\n"
"  height: 100%;\n"
"  background-color: #ffffff;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  border-radius: 10px;\n"
"  gap: 20px;\n"
"  display: flex;\n"
"  padding: 5px 20px 5px 20px;\n"
"  border-top-left-radius: 10px;\n"
"  border-top-right-radius: 10px;\n"
"  border-bottom-left-radius: 10px;\n"
"  border-bottom-right-radius: 10px;}\n"
"QPushButton:hover {\n"
"background: #FFF1ED;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/ui\\../img/add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEventBtn.setIcon(icon)
        self.addEventBtn.setIconSize(QtCore.QSize(28, 28))
        self.addEventBtn.setAutoRepeatInterval(100)
        self.addEventBtn.setObjectName("addEventBtn")
        self.horizontalLayout.addWidget(self.addEventBtn)
        self.eventsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.eventsBtn.setGeometry(QtCore.QRect(0, 110, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventsBtn.sizePolicy().hasHeightForWidth())
        self.eventsBtn.setSizePolicy(sizePolicy)
        self.eventsBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.eventsBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.eventsBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.eventsBtn.setAutoFillBackground(False)
        self.eventsBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  gap: 4px;}\n"
"QPushButton:hover {\n"
"background: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}\n"
"")
        self.eventsBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/ui\\../img/events_selected_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eventsBtn.setIcon(icon1)
        self.eventsBtn.setIconSize(QtCore.QSize(85, 100))
        self.eventsBtn.setCheckable(False)
        self.eventsBtn.setAutoDefault(False)
        self.eventsBtn.setDefault(False)
        self.eventsBtn.setFlat(True)
        self.eventsBtn.setObjectName("eventsBtn")
        self.calendarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.calendarBtn.setGeometry(QtCore.QRect(0, 220, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarBtn.sizePolicy().hasHeightForWidth())
        self.calendarBtn.setSizePolicy(sizePolicy)
        self.calendarBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.calendarBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calendarBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.calendarBtn.setAutoFillBackground(False)
        self.calendarBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  gap: 4px;}\n"
"QPushButton:hover {\n"
"background: #FFF1ED;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}")
        self.calendarBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/ui\\../img/calendar_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendarBtn.setIcon(icon2)
        self.calendarBtn.setIconSize(QtCore.QSize(85, 100))
        self.calendarBtn.setAutoDefault(False)
        self.calendarBtn.setDefault(False)
        self.calendarBtn.setFlat(True)
        self.calendarBtn.setObjectName("calendarBtn")
        self.accountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.accountBtn.setGeometry(QtCore.QRect(0, 340, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountBtn.sizePolicy().hasHeightForWidth())
        self.accountBtn.setSizePolicy(sizePolicy)
        self.accountBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.accountBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.accountBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.accountBtn.setAutoFillBackground(False)
        self.accountBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  gap: 4px;}\n"
"QPushButton:hover {\n"
"background: #FFF1ED;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #FFEAE5;\n"
"}")
        self.accountBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/ui\\../img/account_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountBtn.setIcon(icon3)
        self.accountBtn.setIconSize(QtCore.QSize(85, 100))
        self.accountBtn.setAutoDefault(False)
        self.accountBtn.setDefault(False)
        self.accountBtn.setFlat(True)
        self.accountBtn.setObjectName("accountBtn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(109, 99, 991, 701))
        self.frame.setStyleSheet("background-color: white;\n"
"    border-top-left-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.activeEventsLabel = QtWidgets.QLabel(self.frame)
        self.activeEventsLabel.setGeometry(QtCore.QRect(370, 59, 256, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeEventsLabel.sizePolicy().hasHeightForWidth())
        self.activeEventsLabel.setSizePolicy(sizePolicy)
        self.activeEventsLabel.setMinimumSize(QtCore.QSize(240, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.activeEventsLabel.setFont(font)
        self.activeEventsLabel.setStyleSheet("  color: #281401;\n"
"background-color: none;")
        self.activeEventsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.activeEventsLabel.setObjectName("activeEventsLabel")
        self.activeEventsTable = QtWidgets.QTableWidget(self.frame)
        self.activeEventsTable.setGeometry(QtCore.QRect(100, 121, 800, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeEventsTable.sizePolicy().hasHeightForWidth())
        self.activeEventsTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.activeEventsTable.setFont(font)
        self.activeEventsTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.activeEventsTable.setStyleSheet("background-color: rgb(250, 220, 203);")
        self.activeEventsTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.activeEventsTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.activeEventsTable.setLineWidth(1)
        self.activeEventsTable.setObjectName("tableWidget")
        self.activeEventsTable.setColumnCount(5)
        self.activeEventsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.activeEventsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activeEventsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activeEventsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activeEventsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activeEventsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.activeEventsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.activeEventsTable.setItem(0, 4, item)
        self.activeEventsLabel_2 = QtWidgets.QLabel(self.frame)
        self.activeEventsLabel_2.setGeometry(QtCore.QRect(360, 339, 256, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeEventsLabel_2.sizePolicy().hasHeightForWidth())
        self.activeEventsLabel_2.setSizePolicy(sizePolicy)
        self.activeEventsLabel_2.setMinimumSize(QtCore.QSize(240, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.activeEventsLabel_2.setFont(font)
        self.activeEventsLabel_2.setStyleSheet("  color: #281401;\n"
"background-color: none;")
        self.activeEventsLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.activeEventsLabel_2.setObjectName("activeEventsLabel_2")
        self.inactiveEventsTable = QtWidgets.QTableWidget(self.frame)
        self.inactiveEventsTable.setGeometry(QtCore.QRect(100, 390, 800, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inactiveEventsTable.sizePolicy().hasHeightForWidth())
        self.inactiveEventsTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.inactiveEventsTable.setFont(font)
        self.inactiveEventsTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inactiveEventsTable.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.inactiveEventsTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inactiveEventsTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.inactiveEventsTable.setLineWidth(1)
        self.inactiveEventsTable.setObjectName("tableWidget_2")
        self.inactiveEventsTable.setColumnCount(5)
        self.inactiveEventsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.inactiveEventsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inactiveEventsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inactiveEventsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inactiveEventsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inactiveEventsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inactiveEventsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.inactiveEventsTable.setItem(0, 4, item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)

        self.frame.raise_()
        self.topMenu.raise_()
        self.eventsBtn.raise_()
        self.calendarBtn.raise_()
        self.accountBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyEvents"))
        self.categoryText.setText(_translate("MainWindow", "Мероприятия"))
        self.addEventBtn.setText(_translate("MainWindow", "Добавить"))
        self.activeEventsLabel.setText(_translate("MainWindow", "Активные мероприятия"))
        item = self.activeEventsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.activeEventsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.activeEventsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.activeEventsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время"))
        item = self.activeEventsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Бюджет"))
        item = self.activeEventsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Действие"))
        __sortingEnabled = self.activeEventsTable.isSortingEnabled()
        self.activeEventsTable.setSortingEnabled(False)
        self.activeEventsTable.setSortingEnabled(__sortingEnabled)
        self.activeEventsLabel_2.setText(_translate("MainWindow", "Неактивные мероприятия"))
        item = self.inactiveEventsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.inactiveEventsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.inactiveEventsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.inactiveEventsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время"))
        item = self.inactiveEventsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Бюджет"))
        item = self.inactiveEventsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Действие"))
        __sortingEnabled = self.inactiveEventsTable.isSortingEnabled()
        self.inactiveEventsTable.setSortingEnabled(False)
        self.inactiveEventsTable.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
